# Generated by Django 3.1.7 on 2021-04-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartFailure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('anaemia', models.IntegerField()),
                ('creatinine_phosphokinase', models.FloatField()),
                ('diabetes', models.IntegerField()),
                ('ejection_fraction', models.FloatField()),
                ('high_blood_pressure', models.IntegerField()),
                ('platelets', models.FloatField()),
                ('serum_creatinine', models.FloatField()),
                ('serum_sodium', models.FloatField()),
                ('sex', models.IntegerField()),
                ('smoking', models.IntegerField()),
                ('time', models.IntegerField()),
                ('death_event', models.IntegerField()),
            ],
            options={
                'db_table': 'heart_failure',
            },
        ),
    ]
