# Generated by Django 3.1.7 on 2021-03-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsedCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_car_model', models.CharField(max_length=100, null=True)),
                ('used_car_year', models.IntegerField(max_length=11, null=True)),
                ('used_car_price', models.IntegerField(max_length=11, null=True)),
                ('used_car_transmission', models.CharField(max_length=100, null=True)),
                ('used_car_mileage', models.IntegerField(max_length=11, null=True)),
                ('used_car_fuel_type', models.CharField(max_length=100, null=True)),
                ('used_car_tax', models.IntegerField(max_length=11, null=True)),
                ('used_car_mpg', models.FloatField(null=True)),
                ('used_car_engine_size', models.FloatField(null=True)),
            ],
        ),
    ]
