# Generated by Django 3.1.7 on 2021-03-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedcar',
            name='used_car_mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='used_car_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='used_car_tax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='used_car_year',
            field=models.IntegerField(null=True),
        ),
    ]
