# Generated by Django 3.1.7 on 2021-03-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210325_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedcar',
            old_name='used_car_engine_size',
            new_name='enginesize',
        ),
        migrations.RenameField(
            model_name='usedcar',
            old_name='used_car_fuel_type',
            new_name='fueltype',
        ),
        migrations.RenameField(
            model_name='usedcar',
            old_name='used_car_mileage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='usedcar',
            old_name='used_car_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='usedcar',
            old_name='used_car_mpg',
            new_name='mpg',
        ),
        migrations.RenameField(
            model_name='usedcar',
            old_name='used_car_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='usedcar',
            old_name='used_car_tax',
            new_name='tax',
        ),
        migrations.RenameField(
            model_name='usedcar',
            old_name='used_car_transmission',
            new_name='transmission',
        ),
        migrations.RenameField(
            model_name='usedcar',
            old_name='used_car_year',
            new_name='year',
        ),
    ]
