# Generated by Django 3.1.7 on 2021-03-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210325_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartFailure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('anaemia', models.BinaryField()),
                ('creatinine_phosphokinase', models.FloatField()),
                ('diabetes', models.BinaryField()),
                ('ejection_fraction', models.FloatField()),
                ('high_blood_pressure', models.BinaryField()),
                ('platelets', models.FloatField()),
                ('serum_creatinine', models.FloatField()),
                ('serum_sodium', models.FloatField()),
                ('sex', models.BinaryField()),
                ('smoking', models.BinaryField()),
                ('time', models.IntegerField()),
                ('death_event', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='UsedCar',
        ),
    ]
